export const dummyPapers = [
  {
    id: "paper_001",
    projectId: "project_001",
    title: "Serum IL-6 as a Predictive Biomarker for Immunotherapy Response in NSCLC",
    authors: "Chen et al.",
    journal: "Journal of Thoracic Oncology",
    year: 2024,
    uploadedAt: "2026-05-13",
    status: "processed",
    extractedMethods: true,
    pageCount: 14,
  },
  {
    id: "paper_002",
    projectId: "project_001",
    title: "Inflammatory Markers and Overall Survival in Advanced Lung Cancer: A Meta-Analysis",
    authors: "Hoffman & Patel et al.",
    journal: "The Lancet Oncology",
    year: 2023,
    uploadedAt: "2026-05-18",
    status: "processed",
    extractedMethods: true,
    pageCount: 22,
  },
  {
    id: "paper_003",
    projectId: "project_001",
    title: "Cox Proportional Hazards Models in Clinical Oncology Trials",
    authors: "Williams et al.",
    journal: "Statistics in Medicine",
    year: 2022,
    uploadedAt: "2026-06-01",
    status: "pending",
    extractedMethods: false,
    pageCount: 18,
  },
  {
    id: "paper_101",
    projectId: "project_002",
    title: "Depressive Symptom Severity and Glycemic Control in Adults with Type 2 Diabetes",
    authors: "Okonkwo et al.",
    journal: "Diabetes Care",
    year: 2025,
    uploadedAt: "2026-06-20",
    status: "processed",
    extractedMethods: true,
    pageCount: 11,
  },
]

export const dummyDatasets = [
  {
    id: "dataset_001",
    projectId: "project_001",
    filename: "nsclc_cohort_312_patients.csv",
    uploadedAt: "2026-05-14",
    rows: 312,
    columns: 28,
    status: "profiled",
    missingnessPercent: 4.2,
    detectedStructure: "Patient-level clinical data with survival endpoints",
    keyVariables: ["patient_id", "age", "sex", "il6_baseline", "crp_baseline", "pfs_months", "pfs_event", "os_months", "os_event", "treatment_arm"],
  },
  {
    id: "dataset_101",
    projectId: "project_002",
    filename: "t2d_depression_cohort_150_patients.csv",
    uploadedAt: "2026-06-21",
    rows: 150,
    columns: 14,
    status: "profiled",
    missingnessPercent: 3.1,
    detectedStructure: "Patient-level cross-sectional clinical data",
    keyVariables: ["patient_id", "age", "sex", "phq9_score", "hba1c", "medication_adherence_pct", "diabetes_duration_years"],
  },
]

export const dummyAnalyses = [
  {
    id: "analysis_003",
    projectId: "project_001",
    name: "Cox Regression — IL-6 adjusted for age, sex, stage",
    type: "Cox Proportional Hazards",
    runAt: "2026-06-16T14:32:00Z",
    status: "completed",
    primaryResult: "HR 1.42 (95% CI: 1.11–1.82), p = 0.006",
    agent: "Stats Agent",
    scriptUsed: "survival_cox_adjusted.py",
    provenance: "Rulebook + New reasoning",
  },
  {
    id: "analysis_002",
    projectId: "project_001",
    name: "Kaplan-Meier — PFS by IL-6 tertile",
    type: "Kaplan-Meier Survival",
    runAt: "2026-06-15T10:14:00Z",
    status: "completed",
    primaryResult: "Log-rank p = 0.003 across IL-6 tertiles",
    agent: "Stats Agent",
    scriptUsed: "survival_kaplan_meier.py",
    provenance: "Rulebook",
  },
  {
    id: "analysis_001",
    projectId: "project_001",
    name: "Descriptive statistics — baseline cohort",
    type: "Descriptive Statistics",
    runAt: "2026-05-15T09:00:00Z",
    status: "completed",
    primaryResult: "Mean age 63.4 ± 9.1 yrs; 58% male; median IL-6 18.2 pg/mL",
    agent: "Data Agent",
    scriptUsed: "clinical_baseline_table.py",
    provenance: "Deterministic computation",
  },
  {
    id: "analysis_101",
    projectId: "project_002",
    name: "Logistic Regression — PHQ-9 predicting poor glycemic control",
    type: "Logistic Regression",
    runAt: "2026-06-22T11:00:00Z",
    status: "queued",
    primaryResult: "Not yet run",
    agent: "Stats Agent",
    scriptUsed: "logistic_regression.py",
    provenance: "New reasoning",
  },
]

export const dummyCharts = [
  {
    id: "chart_002",
    projectId: "project_001",
    name: "Kaplan-Meier — PFS stratified by IL-6 tertile",
    analysisId: "analysis_002",
    createdAt: "2026-06-15T10:18:00Z",
    type: "Kaplan-Meier curve",
    exportFormats: ["PNG", "SVG", "PDF"],
  },
  {
    id: "chart_001",
    projectId: "project_001",
    name: "Forest plot — Cox regression covariates",
    analysisId: "analysis_003",
    createdAt: "2026-06-16T14:45:00Z",
    type: "Forest plot",
    exportFormats: ["PNG", "SVG"],
  },
]

export const dummyResearchQuestions = [
  {
    id: "rq_001",
    projectId: "project_001",
    question: "Are baseline serum IL-6 levels independently associated with progression-free survival after adjusting for age, sex, and disease stage?",
    createdAt: "2026-05-14",
    status: "analyzed",
    linkedAnalyses: ["analysis_001", "analysis_002", "analysis_003"],
  },
  {
    id: "rq_002",
    projectId: "project_001",
    question: "Does CRP add independent prognostic value beyond IL-6 in a multivariate Cox model?",
    createdAt: "2026-06-10",
    status: "pending",
    linkedAnalyses: [],
  },
  {
    id: "rq_101",
    projectId: "project_002",
    question: "Is depressive symptom severity (PHQ-9) associated with poor glycemic control (HbA1c ≥ 8%), independent of medication adherence?",
    createdAt: "2026-06-21",
    status: "pending",
    linkedAnalyses: [],
  },
]

export const dummyActivityFeed = [
  { id: "a8", projectId: "project_001", timestamp: "2026-06-16T14:45:00Z", agent: "Visualization Agent", action: "Generated forest plot for Cox regression (chart_001)", type: "chart" },
  { id: "a7", projectId: "project_001", timestamp: "2026-06-16T14:32:00Z", agent: "Stats Agent", action: "Completed adjusted Cox regression — HR 1.42 (p=0.006)", type: "analysis" },
  { id: "a6", projectId: "project_001", timestamp: "2026-06-16T14:28:00Z", agent: "Critic Agent", action: "Verified proportional hazards assumption — no violation detected", type: "verification" },
  { id: "a5", projectId: "project_001", timestamp: "2026-06-16T14:20:00Z", agent: "Memory Agent", action: "Created rulebook entry: pfs_months is survival time, pfs_event is event indicator", type: "rulebook" },
  { id: "a4", projectId: "project_001", timestamp: "2026-06-15T10:18:00Z", agent: "Visualization Agent", action: "Generated Kaplan-Meier curve stratified by IL-6 tertile", type: "chart" },
  { id: "a3", projectId: "project_001", timestamp: "2026-06-15T10:14:00Z", agent: "Stats Agent", action: "Completed Kaplan-Meier analysis — log-rank p=0.003", type: "analysis" },
  { id: "a2", projectId: "project_001", timestamp: "2026-06-15T09:58:00Z", agent: "Stats Agent", action: "Recommended Cox regression and Kaplan-Meier for survival endpoint (RQ-001)", type: "recommendation" },
  { id: "a1", projectId: "project_001", timestamp: "2026-06-14T11:30:00Z", agent: "Paper Agent", action: "Extracted methods, variables, and endpoints from Chen et al. 2024", type: "paper" },
  { id: "a9", projectId: "project_002", timestamp: "2026-06-21T09:30:00Z", agent: "Paper Agent", action: "Extracted methods and variables from Okonkwo et al. 2025", type: "paper" },
  { id: "a10", projectId: "project_002", timestamp: "2026-06-22T11:00:00Z", agent: "Planner Agent", action: "Queued logistic regression for PHQ-9 → glycemic control", type: "recommendation" },
]

export const dummyRulebookEntries = [
  { id: "rule_0041", projectId: "project_001", scope: "project", text: "pfs_months is the survival time variable for this project", confidence: "high", source: "Memory Agent — auto-detected from dataset + paper" },
  { id: "rule_0042", projectId: "project_001", scope: "project", text: "pfs_event is the censoring indicator (1=event, 0=censored)", confidence: "high", source: "User confirmed" },
  { id: "rule_0043", projectId: "project_001", scope: "project", text: "Prefer Cox regression adjusted for age, sex, and stage_iv for all survival endpoints", confidence: "high", source: "User approved recommendation" },
  { id: "rule_0044", projectId: "project_001", scope: "dataset", text: "Do not use t-test for stage_iv — it is an ordinal variable", confidence: "high", source: "Critic Agent flag" },
]

export const dummyAgentStatus = [
  { name: "Planner Agent", promptVersion: "v3", lastActive: "2026-06-16T14:20:00Z", status: "idle" },
  { name: "Paper Agent", promptVersion: "v2", lastActive: "2026-06-14T11:30:00Z", status: "idle" },
  { name: "Data Agent", promptVersion: "v2", lastActive: "2026-06-15T09:00:00Z", status: "idle" },
  { name: "Stats Agent", promptVersion: "v8", lastActive: "2026-06-16T14:32:00Z", status: "idle" },
  { name: "Code Agent", promptVersion: "v4", lastActive: "2026-06-16T14:32:00Z", status: "idle" },
  { name: "Visualization Agent", promptVersion: "v3", lastActive: "2026-06-16T14:45:00Z", status: "idle" },
  { name: "Report Agent", promptVersion: "v2", lastActive: "2026-06-10T09:00:00Z", status: "idle" },
  { name: "Critic Agent", promptVersion: "v5", lastActive: "2026-06-16T14:28:00Z", status: "idle" },
  { name: "Memory Agent", promptVersion: "v3", lastActive: "2026-06-16T14:20:00Z", status: "idle" },
]
